pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        echo "Run build"
        sh 'chmod +x projects/jenkins/build_script.sh'
        sh './projects/jenkins/build_script.sh'
      }
    }
    stage('Test') {
      parallel {
       stage('Test On Windows') {
         steps {
           echo "Running tests on Windows"
         }
       }
       stage('Test On Linux') {
         steps {
           echo "Running tests on Linux"
         }
       }
     }
    }
  }
}
