pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        echo "Run build"
        sh 'chmod +x projects/jenkins/build_script.sh'
        sh './projects/jenkins/build_script.sh'
      }
    }
    stage('Test') {
      steps {
        echo "Run tests"
      }
    }
  }
}
